- name : Install and run nginx
  become : yes # for root access
  hosts : web
  tasks :
  - name: install nginx
    ansible.builtin.package:
    name: install nginx
    state: installed
  - name: run the nginx
    ansible.builtin.service:
    name: running nginx
    state: started
  - name: installed and running the nginx
    ansible.builtin.debug:
    msg: "Installed nginx and running succfully now you can start the processes"
  

