- name: installing nginx and run
  hosts: web
  become: yes
  tasks:
  - name: installing nginx
    ansible.builtin.package:
      name: nginx
      state: present
  - name: running nginx
    ansible.builtin.service:
      name: run nginx
      state: started
      enabled: yes
  - name: showing message
    ansible.builtin.debug:
      msg: "Hi there installed nginx and running succfully enjoy"
  

