- name: using vars in ansible
  hosts: web
  vars:
    CROUSE: "Ansible"
    DURATION: "10 HRS"
    TIME: "7:00 PM"
  tasks:
    - name: printing the vars
      ansible.builtin.debug:
        msg: "Hi venkatesh your {{COURSE}}, {{DURATION}}: is, and the {{TIME}}: get start be focuses" 