- name: Playing with variables
  hosts: web
  vars:
    NAME: {{venkatesh}}
    CROUSE: {{Ansible}}
    FOCUS: {{for job change}}
  tasks:
    - name: print the info
      ansible.builtin.debug:
        msg: "This is {{NAME}} learing {{CROUSE}} aws looking {{FOCUS}}"