- name: variable to print
  hosts: web
  vars:
    COURSE: "devops with AWS"
    DURATION: "120hr"
    TRAINER: "siva"
  tasks: 
  - name: print the infromation
    ansible.builtin.debug:
      msg: "Hi this venkatesh started training in {{COURSE}}, duration is :{{DURATION}}, Trainer is:{{TRAINER}}"