- name: var files
  hosts: web
  var_files:
    - vars.yaml
  tasks:
  - name: var files
      ansible.builtin.debug:
      msg: "Hi this venkatesh started training in {{COURSE}}, duration is :{{DURATION}}, Trainer is:{{TRAINER}}"