- name : Learing varables with var files
  hosts: web
  vars_files:
    - vars.yaml
  tasks:
  - name: Print the info gettin through var files
    ansible.builtin.debug:
      msg: "Hi this is vekatesh started tarining {{COURSE}} duration {{DURATION}}, trainer name {{TRAINER}}"

