- name: Varaibles from files
  hosts: web
  var_files:
    - vars.yaml
  tasks:
  - name: print the course info
    ansible.builtin.debug:
      msg: "Hi this venkatesh started training in {{COURSE}}, duration is :{{DURATION}}, Trainer is:{{TRAINER}}"