- name: Varables promts
  hosts: web
  vars_prompt:
    - name: CROUSE
      prompt: Please Enter the Crouse name
    - name: DURATION
      prompt: Please Enter the Crouse duration
    - name: TRAINER
      prompt: Please Enter the Trainer name
  tasks:
    - name: printing the infromation
      ansible.builtin.debug:
        msg: "Hiii started {{CROUSE}}, duration was {{DURATION}}, trainer name is {{TRAINER}}"