- name: print the infromation
  hosts: web
  vars:
      COURSE: "This is devops from variables"
      TRAINER: "Venkatesh"
  vars_files:
    - vars.yaml 
  vars_prompt:
    - name: printing the prompt type varaibles
      prompt: please enter coruse name
      private: false
  tasks:
    - name: print the information
      vars:
        COURSE: "DEVOPS with task level varaibles"
    - name: checking which will take first priporty
      ansible.builtin.debug:
        msg: "Hi this {{COURSE}}, tainer name{{TRAINER}}"
  
  

