- name: variable to print
  hosts: web
  vars:
    COURSE: "devops with AWS"
    DURATION: "120hr"
    TRAINER: "siva"
  vars_prompt:
  - name: COURSE
    prompt: please enter the course name
    private: false
  tasks: 
  - name: print the infromation
    vars:
      COURSE: "devops with AWS"
      DURATION: "120hr"
      TRAINER: "siva"
    ansible.builtin.debug:
      msg: "Hi this venkatesh started training in {{COURSE}}"