- name: testing conditions
  hosts: local
  connection: local
  var_prompt: my_number
  - name: my_number
    prompt: please enter any number
    private: false
  tasks:
  - name: print this less than 10
    ansible.builtin.debug:
      msg: "Given number is {{my_number}} less than 10"
    when: my_number | int < 10
  - name: print this if grethan 10
    ansible.builtin.debug:
      msg: "Given number is {{my_number}} greater than 10"
    when: my_number | > 10