- name: using loops install pcks
  hosts: web
  become: yes
  tasks: 
  - name: installing packages
    ansible.builtin.package:
      name: "{{item}}"
      state: present
    loop:
    - mysql
    - nginx
    - postfix