- name: function and filters
  hosts: local
  connection: local
  tasks:
  - name: print default
    ansible.builtin.debug:
      msg: "helo {{course | default ('Ansible')}}"
    
  - name: convert to upper case
    vars: 
      greeting: "hello venki"
    ansible.builtin.debug:
      msg: "{{ greeting | upper }}"
    
  - name: convert to lower case
    vars: 
      greeting: "HELLO WORLD"
    ansible.builtin.debug:
      msg: "{{ greeting | lower }}"