- name: create ec2 and r53 record
  hosts: local
  connection: local
  vars:
    subnet_id: subnet-0b6f121bfe637cf25 
    sg_id: sg-03cd9366e2b4cccae
    ami_id: ami-09c813fb71547fc4f
    instance:
    - mysql
    - backend
    - frontend
    zone: vvsmgold.online
  tasks:
  - name: create ec2 instance
    amazon.aws.ec2_instance:
      name: "{{item}}"
      vpc_subnet_id: "{{subnet_id}}"
      instance_type: "t3.micro"
      security_group: "{{sg_id}}"
      image_id: "{{ami_id}}"
    loop: "{{ instance }}"
    register: ec2_instance

  - name: getting ip
    ansible.builtin.debug:
      msg: "{{ ec2_instance }}"

# private ip route record
  - name: create r53 records
    amazon.aws.route53:
      state: present
      zone: "{{ zone }}"
      record: "{{ item.item }}.{{ zone }}"
      type: A
      ttl: 1
      value: "{{ item.instances[0].private_ip_address }}"
      wait: true
      overwrite: true
    loop: "{{ ec2_instance.results }}"

# piblic ip need for front end

  - name: create r53 records
    amazon.aws.route53:
      state: present
      zone: "{{ zone }}"
      record: "{{ item.item }}.{{ zone }}"
      type: A
      ttl: 1
      value: "{{ item.instances[0].public_ip_address }}"
      wait: true
      overwrite: true
    loop: "{{ ec2_instance.results }}"
    when: item.item == "frontend"

